import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

/**
 * These run against `wrangler dev` serving the real build, not against Vite.
 * Everything here is invisible to the other specs: the asset layer decides
 * what reaches the Worker at all, and the Worker is what injects the tags
 * crawlers read.
 *
 * `worker/index.test.ts` covers the Worker's logic with a stubbed `env`.
 * What only this file can show is the two layers wired together.
 */

const here = dirname(fileURLToPath(import.meta.url));
const builtShell = readFileSync(resolve(here, "../../dist/index.html"), "utf8");

/**
 * `twitter:site` is emitted by `buildMetaTags` and appears nowhere in the
 * built shell, so its presence proves the Worker produced the response
 * rather than the asset store handing back `index.html` untouched. That
 * distinction is the whole point of these tests and cannot be made from the
 * status code, which is 200 either way.
 */
const WORKER_ONLY_TAG = 'name="twitter:site"';

test("the built shell carries no worker tags, so the marker is meaningful", () => {
    expect(builtShell).not.toContain(WORKER_ONLY_TAG);
});

test.describe("routing", () => {
    // Usernames are `^[a-zA-Z0-9._]+$`. When the asset check tested the whole
    // pathname for a trailing extension, `/profile/john.smith` was mistaken
    // for a file and handed to the asset store, which returns the untouched
    // shell under `not_found_handling: single-page-application`. The page
    // still rendered; what was lost was every tag a crawler reads.
    for (const username of ["john.smith", "alice.dev", "bob.io"]) {
        test(`the worker handles /profile/${username}`, async ({ request }) => {
            const res = await request.get(`/profile/${username}`);

            expect(res.status()).toBe(200);
            expect(res.headers()["content-type"]).toContain("text/html");
            expect(await res.text()).toContain(WORKER_ONLY_TAG);
        });
    }

    test("the worker handles a plain username too", async ({ request }) => {
        const res = await request.get("/profile/alice");

        expect(res.status()).toBe(200);
        expect(await res.text()).toContain(WORKER_ONLY_TAG);
    });

    test("a real asset is served as itself, not as the shell", async ({
        request,
    }) => {
        const res = await request.get("/favicon.svg");

        expect(res.status()).toBe(200);
        expect(res.headers()["content-type"]).toContain("image/svg+xml");
    });
});

test.describe("meta injection", () => {
    test("the shell's placeholder tags are replaced, not duplicated", async ({
        request,
    }) => {
        const html = await (await request.get("/")).text();

        expect(html.match(/property="og:title"/g)).toHaveLength(1);
        expect(html.match(/name="description"/g)).toHaveLength(1);
    });
});

test.describe("/sitemap.xml", () => {
    test("is generated by the worker rather than looked up as a file", async ({
        request,
    }) => {
        const res = await request.get("/sitemap.xml");

        expect(res.status()).toBe(200);
        expect(res.headers()["content-type"]).toContain("application/xml");

        const xml = await res.text();
        expect(xml).toContain("<urlset");
        // Every static route must be advertised. These drifted from the
        // router once already, which is why `worker/static-routes.ts` exists.
        for (const path of ["/", "/explore", "/terms", "/privacy"]) {
            expect(xml).toContain(
                `<loc>https://developernetwork.net${path === "/" ? "/" : path}</loc>`,
            );
        }
    });
});
