import { describe, expect, it, vi } from "vitest";

// Importing the router pulls in every page, and those reach the persisted
// auth store — stub storage before any module is evaluated.
vi.hoisted(() => {
    const _map = new Map<string, string>();
    vi.stubGlobal("localStorage", {
        getItem: (key: string) => _map.get(key) ?? null,
        setItem: (key: string, value: string) => {
            _map.set(key, String(value));
        },
        removeItem: (key: string) => {
            _map.delete(key);
        },
        clear: () => {
            _map.clear();
        },
        get length() {
            return _map.size;
        },
        key: (i: number) => [..._map.keys()][i] ?? null,
    });
});

import { router } from "./router";
import { STATIC_ROUTES } from "../../worker/static-routes";

/**
 * The sitemap is generated by the Cloudflare Worker, which is a separate
 * TypeScript project from the app. Nothing but this test connects the routes
 * it advertises to the routes the router actually serves, and the two drifted
 * before: the sitemap published `/terms-of-service` and `/privacy-policy`
 * while the router declared `/terms` and `/privacy`.
 */
describe("sitemap static routes", () => {
    const declaredPaths = new Set(
        router.routes.map((route) => route.path).filter(Boolean),
    );

    it("advertises only paths the router declares", () => {
        const missing = STATIC_ROUTES.map((route) => route.url).filter(
            (url) => !declaredPaths.has(url),
        );

        expect(missing).toEqual([]);
    });

    it("does not rely on the catch-all to serve a sitemap URL", () => {
        // `*` redirects to `/`, so a stale sitemap entry would still answer 200
        // and silently look healthy while pointing crawlers at the homepage.
        expect(declaredPaths.has("*")).toBe(true);
        expect(STATIC_ROUTES.map((route) => route.url)).not.toContain("*");
    });

    it("keeps the legal pages in the sitemap", () => {
        const urls = STATIC_ROUTES.map((route) => route.url);

        expect(urls).toContain("/terms");
        expect(urls).toContain("/privacy");
    });
});
